In [2]:
import cv2 as cv

In [2]:
%pip install opencv-python matplotlib

  Obtaining dependency information for opencv-python from https://files.pythonhosted.org/packages/32/a6/4321f0f30ee11d6d85f49251d417f4e885fe7638b5ac50b7e3c80cccf141/opencv_python-4.8.0.76-cp37-abi3-macosx_11_0_arm64.whl.metadata
  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/f6/22/9c31044ff7339c63727a135872e5cb59564f11625372a81c3eebf148f4af/matplotlib-3.7.2-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/88/e3/696e96ee197b1f60242d12b215332af9fc1961c81990c8b5630b89b34ce6/contourpy-1.1.0-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Obtaining dependency information for fonttools>=4.22.0 from https://files.pythonhosted.org/packages/1f/80/c5ce42faa7dec3c22fe587e56e141c7416c19a13a96bd4972bf1b55cb494/fonttools-4.42.1-cp311-cp311-macosx_10_9_universal2.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.0/151.0 kB 1.5 MB/s eta 0:00:00a 0:00:0

In [3]:
image = cv.imread(r"a.png")

In [4]:
type(image)

numpy.ndarray

In [5]:
image.shape

(270, 394, 3)

In [6]:
image.size

319140

In [7]:
print(image)

[[[92 92 92]
  [92 92 92]
  [92 92 92]
  ...
  [92 92 92]
  [92 92 92]
  [92 92 92]]

 [[92 92 92]
  [92 92 92]
  [92 92 92]
  ...
  [92 92 92]
  [92 92 92]
  [92 92 92]]

 [[92 92 92]
  [92 92 92]
  [92 92 92]
  ...
  [92 92 92]
  [92 92 92]
  [92 92 92]]

 ...

 [[92 92 92]
  [92 92 92]
  [92 92 92]
  ...
  [92 92 92]
  [92 92 92]
  [92 92 92]]

 [[92 92 92]
  [92 92 92]
  [92 92 92]
  ...
  [92 92 92]
  [92 92 92]
  [92 92 92]]

 [[92 92 92]
  [92 92 92]
  [92 92 92]
  ...
  [92 92 92]
  [92 92 92]
  [92 92 92]]]


In [8]:
image.dtype

dtype('uint8')

In [12]:
cv.imshow("a", image)

In [13]:
import matplotlib.pyplot as plt

In [ ]:
plt.imshow(image)

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\selector_events.py", line 119, in _read_from_self
    data = self._ssock.recv(4096)
           ^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 80, in _run


: 